// Code generated by protoc-gen-go.
// source: src/main/proto/demo.proto
// DO NOT EDIT!

/*
Package protos_wrapper is a generated protocol buffer package.

It is generated from these files:
	src/main/proto/demo.proto

It has these top-level messages:
	Peticion
	Respuesta
*/
package protos_wrapper

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Peticion struct {
	Id       int32   `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	User     string  `protobuf:"bytes,2,opt,name=user" json:"user,omitempty"`
	Password string  `protobuf:"bytes,3,opt,name=password" json:"password,omitempty"`
	Product  string  `protobuf:"bytes,4,opt,name=product" json:"product,omitempty"`
	Amount   float32 `protobuf:"fixed32,5,opt,name=amount" json:"amount,omitempty"`
	Account  string  `protobuf:"bytes,6,opt,name=account" json:"account,omitempty"`
	Date     int64   `protobuf:"varint,7,opt,name=date" json:"date,omitempty"`
}

func (m *Peticion) Reset()                    { *m = Peticion{} }
func (m *Peticion) String() string            { return proto.CompactTextString(m) }
func (*Peticion) ProtoMessage()               {}
func (*Peticion) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Peticion) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Peticion) GetUser() string {
	if m != nil {
		return m.User
	}
	return ""
}

func (m *Peticion) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *Peticion) GetProduct() string {
	if m != nil {
		return m.Product
	}
	return ""
}

func (m *Peticion) GetAmount() float32 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *Peticion) GetAccount() string {
	if m != nil {
		return m.Account
	}
	return ""
}

func (m *Peticion) GetDate() int64 {
	if m != nil {
		return m.Date
	}
	return 0
}

type Respuesta struct {
	Id    int32 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Rcode int32 `protobuf:"varint,2,opt,name=rcode" json:"rcode,omitempty"`
	// Types that are valid to be assigned to Resultado:
	//	*Respuesta_Error
	//	*Respuesta_Confirmacion
	Resultado isRespuesta_Resultado `protobuf_oneof:"resultado"`
}

func (m *Respuesta) Reset()                    { *m = Respuesta{} }
func (m *Respuesta) String() string            { return proto.CompactTextString(m) }
func (*Respuesta) ProtoMessage()               {}
func (*Respuesta) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type isRespuesta_Resultado interface {
	isRespuesta_Resultado()
}

type Respuesta_Error struct {
	Error string `protobuf:"bytes,3,opt,name=error,oneof"`
}
type Respuesta_Confirmacion struct {
	Confirmacion int32 `protobuf:"varint,4,opt,name=confirmacion,oneof"`
}

func (*Respuesta_Error) isRespuesta_Resultado()        {}
func (*Respuesta_Confirmacion) isRespuesta_Resultado() {}

func (m *Respuesta) GetResultado() isRespuesta_Resultado {
	if m != nil {
		return m.Resultado
	}
	return nil
}

func (m *Respuesta) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Respuesta) GetRcode() int32 {
	if m != nil {
		return m.Rcode
	}
	return 0
}

func (m *Respuesta) GetError() string {
	if x, ok := m.GetResultado().(*Respuesta_Error); ok {
		return x.Error
	}
	return ""
}

func (m *Respuesta) GetConfirmacion() int32 {
	if x, ok := m.GetResultado().(*Respuesta_Confirmacion); ok {
		return x.Confirmacion
	}
	return 0
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*Respuesta) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _Respuesta_OneofMarshaler, _Respuesta_OneofUnmarshaler, _Respuesta_OneofSizer, []interface{}{
		(*Respuesta_Error)(nil),
		(*Respuesta_Confirmacion)(nil),
	}
}

func _Respuesta_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*Respuesta)
	// resultado
	switch x := m.Resultado.(type) {
	case *Respuesta_Error:
		b.EncodeVarint(3<<3 | proto.WireBytes)
		b.EncodeStringBytes(x.Error)
	case *Respuesta_Confirmacion:
		b.EncodeVarint(4<<3 | proto.WireVarint)
		b.EncodeVarint(uint64(x.Confirmacion))
	case nil:
	default:
		return fmt.Errorf("Respuesta.Resultado has unexpected type %T", x)
	}
	return nil
}

func _Respuesta_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*Respuesta)
	switch tag {
	case 3: // resultado.error
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeStringBytes()
		m.Resultado = &Respuesta_Error{x}
		return true, err
	case 4: // resultado.confirmacion
		if wire != proto.WireVarint {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeVarint()
		m.Resultado = &Respuesta_Confirmacion{int32(x)}
		return true, err
	default:
		return false, nil
	}
}

func _Respuesta_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*Respuesta)
	// resultado
	switch x := m.Resultado.(type) {
	case *Respuesta_Error:
		n += proto.SizeVarint(3<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(len(x.Error)))
		n += len(x.Error)
	case *Respuesta_Confirmacion:
		n += proto.SizeVarint(4<<3 | proto.WireVarint)
		n += proto.SizeVarint(uint64(x.Confirmacion))
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

func init() {
	proto.RegisterType((*Peticion)(nil), "protos.wrapper.Peticion")
	proto.RegisterType((*Respuesta)(nil), "protos.wrapper.Respuesta")
}

func init() { proto.RegisterFile("src/main/proto/demo.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 276 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x64, 0x90, 0x3d, 0x4e, 0x03, 0x31,
	0x10, 0x85, 0xc9, 0xcf, 0x6e, 0x92, 0x01, 0xa5, 0xb0, 0x10, 0x32, 0x34, 0xa0, 0x88, 0x02, 0x9a,
	0x4d, 0xc1, 0x0d, 0x52, 0x51, 0x46, 0xbe, 0xc1, 0xc4, 0x9e, 0xa0, 0x45, 0xf1, 0xda, 0x1a, 0xdb,
	0x24, 0x05, 0x27, 0xe2, 0x94, 0x38, 0xde, 0x05, 0x09, 0x51, 0xed, 0xfb, 0xde, 0xd3, 0xec, 0x3c,
	0x0f, 0xdc, 0x06, 0xd6, 0x6b, 0x8b, 0x6d, 0xb7, 0xf6, 0xec, 0xa2, 0x5b, 0x1b, 0xb2, 0xae, 0x29,
	0x52, 0x2c, 0xcb, 0x27, 0x34, 0x47, 0x46, 0xef, 0x89, 0x57, 0x5f, 0x23, 0x98, 0x6f, 0x29, 0xb6,
	0xba, 0x75, 0x9d, 0x58, 0xc2, 0xb8, 0x35, 0x72, 0xf4, 0x30, 0x7a, 0xaa, 0x54, 0x56, 0x42, 0xc0,
	0x34, 0x05, 0x62, 0x39, 0xce, 0xce, 0x42, 0x15, 0x2d, 0xee, 0x60, 0xee, 0x31, 0x84, 0xa3, 0x63,
	0x23, 0x27, 0xc5, 0xff, 0x65, 0x21, 0x61, 0x96, 0x7f, 0x6f, 0x92, 0x8e, 0x72, 0x5a, 0xa2, 0x1f,
	0x14, 0x37, 0x50, 0xa3, 0x75, 0xa9, 0x8b, 0xb2, 0xca, 0xc1, 0x58, 0x0d, 0x74, 0x9e, 0x40, 0xad,
	0x4b, 0x50, 0xf7, 0x13, 0x03, 0x9e, 0x77, 0x1b, 0x8c, 0x24, 0x67, 0xd9, 0x9e, 0xa8, 0xa2, 0x57,
	0x9f, 0xb0, 0x50, 0x14, 0x7c, 0xa2, 0x10, 0xf1, 0x5f, 0xd9, 0x6b, 0xa8, 0x58, 0x3b, 0x43, 0xa5,
	0x6d, 0xa5, 0x7a, 0xc8, 0x8b, 0x2b, 0x62, 0x76, 0xdc, 0x77, 0x7d, 0xbd, 0x50, 0x3d, 0x8a, 0x47,
	0xb8, 0xd2, 0xae, 0xdb, 0xb7, 0x6c, 0xf1, 0xfc, 0xf4, 0xd2, 0xb7, 0xca, 0xf1, 0x1f, 0x77, 0x73,
	0x09, 0x0b, 0xa6, 0x90, 0x0e, 0x11, 0x8d, 0xdb, 0x3c, 0xc3, 0xbd, 0xe3, 0xb7, 0xe6, 0x1d, 0x3f,
	0xd0, 0xd2, 0xa9, 0xd5, 0xc3, 0x49, 0x77, 0x69, 0xdf, 0xd0, 0x09, 0xad, 0x3f, 0xd0, 0xa6, 0xde,
	0x96, 0xeb, 0xee, 0xea, 0x92, 0xbc, 0x7c, 0x07, 0x00, 0x00, 0xff, 0xff, 0x3f, 0x9e, 0x92, 0xee,
	0x89, 0x01, 0x00, 0x00,
}
